import { describe, it, expect } from 'vitest';
import { evaluate } from '@elwood-lang/core';
import '../src/index.js'; // registers fromParquet

// A minimal Parquet file (2 rows, 2 columns: name/age) generated and base64-encoded
// We generate this using the .NET toParquet and hardcode the result for cross-platform testing
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

describe('Parquet Extension', () => {
  it('fromParquet reads a round-tripped file', async () => {
    // This test verifies the TS fromParquet can read files created by .NET toParquet.
    // The fixture file is generated by the .NET test and checked in.
    const fixturePath = resolve(__dirname, '../../spec/fixtures/sample.parquet.b64');
    if (!require('fs').existsSync(fixturePath)) {
      console.warn('Skipping: spec/fixtures/sample.parquet.b64 not found (generate with .NET tests first)');
      return;
    }
    const base64 = readFileSync(fixturePath, 'utf-8').trim();
    const r = evaluate('$.fromParquet()', base64);
    expect(r.success).toBe(true);
    expect(Array.isArray(r.value)).toBe(true);
    expect((r.value as any[]).length).toBeGreaterThan(0);
  });

  it('fromParquet returns empty array for invalid input', () => {
    const r = evaluate('$.fromParquet()', 'not-valid-base64!!!');
    expect(r.success).toBe(true);
    expect(r.value).toEqual([]);
  });
});
